In [1]:
import numpy as np

In [2]:
mu = [0.3, 0.7]

mu = np.array(mu)

mu

array([0.3, 0.7])

In [3]:
p = [
    [0.8, 0.2],
    [0.6, 0.4]
    ]

p = np.matrix(p)

In [4]:
p_2 = p.dot(p)

p_2

matrix([[0.76, 0.24],
        [0.72, 0.28]])

In [5]:
mu.dot(p)

matrix([[0.66, 0.34]])

In [6]:
mu.dot(p.dot(p))

matrix([[0.732, 0.268]])

In [7]:
p_3 = p_2.dot(p)

p_3

matrix([[0.752, 0.248],
        [0.744, 0.256]])

In [8]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])

In [9]:
mu.dot(p_2)

matrix([[0.732, 0.268]])

In [10]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])

In [14]:
pi = np.array([0.3, 0.4, 0.3])

p_0_1 = np.array([
    [0.2, 0.3, 0.5],
    [0.3, 0.5, 0.2],
    [0.1, 0.1, 0.8]
])

p_1_2 = np.array([
    [0.1, 0.1, 0.8],
    [0.3, 0.5, 0.2],
    [0.3, 0.5, 0.2]
])

In [15]:
pi.dot(p_0_1)

array([0.21, 0.32, 0.47])

In [17]:
pi.dot(p_0_1.dot(p_1_2))

array([0.258, 0.416, 0.326])

In [18]:
0.4*0.1*0.3

0.012000000000000002