In [2]:
import numpy as np

In [2]:
mu = [0.3, 0.7]

mu = np.array(mu)

mu

array([0.3, 0.7])

In [3]:
p = [
    [0.8, 0.2],
    [0.6, 0.4]
    ]

p = np.matrix(p)

In [4]:
p_2 = p.dot(p)

p_2

matrix([[0.76, 0.24],
        [0.72, 0.28]])

In [5]:
mu.dot(p)

matrix([[0.66, 0.34]])

In [6]:
mu.dot(p.dot(p))

matrix([[0.732, 0.268]])

In [7]:
p_3 = p_2.dot(p)

p_3

matrix([[0.752, 0.248],
        [0.744, 0.256]])

In [8]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])

In [9]:
mu.dot(p_2)

matrix([[0.732, 0.268]])

In [10]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])

# 3.

In [13]:
Pi_0 = np.array([0.3, 0.4, 0.3])

In [11]:
P_01 = np.array([
    [0.2, 0.3, 0.5],
    [0.3, 0.5, 0.2],
    [0.1, 0.1, 0.8]
])

In [12]:
P_12 = np.array([
    [0.1, 0.1, 0.8],
    [0.3, 0.5, 0.2],
    [0.3, 0.5, 0.2]
])

In [15]:
P_01.dot(P_12)

array([[0.26, 0.42, 0.32],
       [0.24, 0.38, 0.38],
       [0.28, 0.46, 0.26]])

# 5

In [17]:
mu = np.array([0.4, 0.6])

P = np.array([
    [0.75, 0.25],
    [0.4, 0.6]
])

In [19]:
P_2 = P.dot(P)
P_2

array([[0.6625, 0.3375],
       [0.54  , 0.46  ]])

In [20]:
P_3 = P.dot(P_2)
P_3

array([[0.631875, 0.368125],
       [0.589   , 0.411   ]])

In [21]:
mu.dot(P_3)

array([0.60615, 0.39385])

# 7

In [14]:
P = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [3/4, 0, 0, 1/4, 0, 0, 0, 0],
    [0, 3/4, 0, 0, 1/4, 0, 0, 0],
    [0, 0, 3/4, 0, 0, 1/4, 0, 0],
    [0, 0, 0, 3/4, 0, 0, 1/4, 0],
    [0, 0, 0, 0, 3/4, 0, 0, 1/4],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

P

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.75, 0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.75, 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [15]:
P_2 = P.dot(P)
P_2[3]

array([0.    , 0.5625, 0.    , 0.    , 0.375 , 0.    , 0.    , 0.0625])

In [16]:
P_3 = P.dot(P_2)
P_3[3]

array([0.421875, 0.      , 0.      , 0.421875, 0.      , 0.      ,
       0.09375 , 0.      ])

# 8

In [17]:
P = np.array([
    [0.9, 0.07, 0.03],
    [0.05, 0.8, 0.15],
    [0.15, 0.15, 0.7]
])

In [19]:
P_2 = P.dot(P)
P_2

array([[0.818 , 0.1235, 0.0585],
       [0.1075, 0.666 , 0.2265],
       [0.2475, 0.2355, 0.517 ]])

# 9.

In [20]:
P = np.array([
    [0.6, 0.3, 0.1],
    [0.2, 0.6, 0.2],
    [0, 0, 1]
])
P

array([[0.6, 0.3, 0.1],
       [0.2, 0.6, 0.2],
       [0. , 0. , 1. ]])

In [21]:
P_2 = P.dot(P)
P_2

array([[0.42, 0.36, 0.22],
       [0.24, 0.42, 0.34],
       [0.  , 0.  , 1.  ]])