In [2]:
import numpy as np

In [6]:
mu = [0.3, 0.7]

mu = np.array(mu)

mu

array([0.3, 0.7])

In [4]:
p = [
    [0.8, 0.2],
    [0.6, 0.4]
    ]

p = np.matrix(p)

In [10]:
p_2 = p.dot(p)

p_2

matrix([[0.76, 0.24],
        [0.72, 0.28]])

In [7]:
mu.dot(p)

matrix([[0.66, 0.34]])

In [8]:
mu.dot(p.dot(p))

matrix([[0.732, 0.268]])

In [11]:
p_3 = p_2.dot(p)

p_3

matrix([[0.752, 0.248],
        [0.744, 0.256]])

In [12]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])

In [14]:
mu.dot(p_2)

matrix([[0.732, 0.268]])

In [15]:
mu.dot(p_3)

matrix([[0.7464, 0.2536]])